---
#- name: Install Java.
#  become: yes
#  apt:
#    name: "{{ riemann_jvm_pkg }}"
#    state: present
#    update_cache: yes
#    cache_valid_time: 3600

- name: Download Riemann deb package.
  become: yes
  get_url:
    url: "{{ riemann_download_url }}"
    dest: "{{ riemann_deb_file_fullpath }}"
    owner: root
    group: root
    mode: "0644"

- name: Download Riemann checksum file.
  become: yes
  get_url:
    url: "{{ riemann_checksum_url }}"
    dest: "{{ riemann_checksum_fullpath }}"

  # If the get_url task didn't change, the checksum
  # won't be available in the registered var, so let's
  # reread the checksum every time.
- name: Read checksum for Riemann deb package.
  stat:
    path: "{{ riemann_deb_file_fullpath }}"
    checksum_algorithm: md5
  register: riemann_download_checksum_result

- name: Validate checksum for deb package.
  command: cat {{ riemann_checksum_fullpath }}
  register: riemann_checksum_result
  changed_when: false
  failed_when: riemann_checksum_result.stdout !=
               "{{ riemann_download_checksum_result.stat.checksum }}  {{ riemann_deb_file_fullpath|basename }}"

- name: Install Riemann deb package.
  become: yes
  apt:
    deb: "{{ riemann_deb_file_fullpath }}"
    state: present
  notify: restart riemann
